# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Turntablism' do
  
  pod 'UIColor-Hex-Swift'
  pod 'YouTubePlayer'
  pod 'Mapbox-iOS-SDK'
  
end

